// Solution catalogue — single source of truth for cards, nav, and /solutions/<slug>/ pages.
// Keep claims verifiable: facts here were taken from each product's codebase and live site.
// status: 'live' | 'soon'
// cta.primary.href starting with '#' scrolls to the on-page enquiry form.

export const categories = [
    { id: 'business', name: 'Business operations', blurb: 'Run finance, stock, sales and people from one system.' },
    { id: 'education', name: 'Education', blurb: 'From primary school to university, plus AI tutoring for learners.' },
    { id: 'finance', name: 'Investing & savings', blurb: 'Consumer fintech for research and community saving.' },
];

export const solutions = [
    {
        slug: 'jadicoq-erp',
        name: 'JADICOQ ERP',
        mark: 'J',
        color: '#1d4ed8',
        category: 'business',
        status: 'live',
        kicker: 'Cloud ERP',
        tagline: 'Run the whole business from one system.',
        summary: 'Accounting, inventory, sales, HR, POS and full industry suites for hotels, hospitals and property — sharing one ledger, one customer record and one set of permissions.',
        points: ['26 modules on one database', 'Hotel, hospital & real-estate suites', 'Free plan, no card required'],
        site: 'https://www.jadicoq.com',
        image: { src: '/img/jadicoq.webp', alt: 'JADICOQ ERP website showing a revenue and cash-flow dashboard', url: 'jadicoq.com' },
        heroChecks: ['Free plan forever', 'No card required', 'Set up the same day'],
        cta: {
            primary: { label: 'Start free', href: 'https://www.jadicoq.com/demo' },
            secondary: { label: 'Book a guided demo', href: '#enquire' },
            pricing: 'https://www.jadicoq.com/pricing',
        },
        audiences: [
            { title: 'Growing SMEs', text: 'Retail, trading, manufacturing and services firms with 10–500 staff replacing spreadsheets and disconnected tools.' },
            { title: 'Hotels', text: 'Reservations, front desk, housekeeping, guest folios and night audit posting straight to the ledger.' },
            { title: 'Hospitals & clinics', text: 'Clinical workflow and the billing it generates, without an interface between them.' },
            { title: 'Property & microfinance', text: 'Leases, rent invoicing, loan portfolios and community relations in the same system.' },
        ],
        modules: [
            { title: 'Finance', icon: 'ledger', items: ['General ledger, budgets and bank reconciliation', 'P&L, balance sheet, cash flow and aged AR/AP', 'Expenses and multi-level approval workflows', 'Multi-currency transactions'] },
            { title: 'Inventory & supply chain', icon: 'box', items: ['Multi-warehouse, bins, batch and expiry tracking', 'Picking, waves and quality inspections', 'Purchasing with RFQ comparison and vendor scorecards', 'Manufacturing: BOMs, work orders, MRP runs'] },
            { title: 'Sales & commerce', icon: 'cart', items: ['POS with split payments, loyalty, tables and offline sync', 'Sales, CRM, e-commerce and subscriptions', 'Bookings, helpdesk and logistics', 'Payments via Paystack and Stripe'] },
            { title: 'People & workplace', icon: 'people', items: ['HR & payroll with biometric attendance', 'Projects, documents and contracts', 'Fleet and plant maintenance', 'Website builder for your own domain'] },
            { title: 'Hospital suite', icon: 'health', items: ['Patients, consultations, e-prescribing and pharmacy', 'Lab, radiology, surgery, wards and emergency triage', 'Billing, pre-authorisation and patient portal', 'Role-based data masking and access audit'] },
            { title: 'Hotel & property suites', icon: 'building', items: ['Room board with housekeeping status', 'Rate plans, RevPAR/ADR analytics and night audit', 'Properties, units, tenants and leases', 'Rent invoicing posted to the ledger'] },
        ],
        highlights: [
            { title: 'Nothing to integrate', text: 'Every module shares one ledger and one customer record, so stock, sales and payroll always reconcile.' },
            { title: 'Security built in', text: 'Two-factor sign-in (TOTP and passkeys), audit log, per-company data isolation and encryption of sensitive records.' },
            { title: 'Open when you need it', text: 'API keys, webhooks, bulk import/export, custom fields and document templates.' },
            { title: 'Designed around recognised standards', text: 'Features designed to support ISO 9001, ISO 55001, IFRS reporting and more — with the evidence trail auditors ask for.' },
        ],
        faq: [
            { q: 'Is there really a free plan?', a: 'Yes. The free plan gives you one app of your choice for one user with unlimited hosting. Paid plans unlock every module and unlimited users.' },
            { q: 'Can you migrate our existing data?', a: 'Yes. Our team handles setup, data migration from spreadsheets or your old system, staff training and ongoing support.' },
            { q: 'Which currencies does billing support?', a: 'Subscriptions can be paid in USD, GBP, EUR or NGN, and your own transactions can be recorded in any currency.' },
        ],
    },
    {
        slug: 'studymate-schools',
        name: 'StudyMate Schools',
        mark: 'S',
        color: '#047857',
        category: 'education',
        status: 'live',
        kicker: 'School management',
        tagline: 'Your whole school, in one platform.',
        summary: 'Attendance, report cards, fees, timetables, CBT exams and payroll — 70+ modules African primary and secondary schools actually use, with portals for staff, parents and students.',
        points: ['70+ modules for primary & secondary', 'Parent, teacher & student portals', 'Free for your first 20 students'],
        site: 'https://www.studymateschools.com',
        image: { src: '/img/studymate-schools.webp', alt: 'StudyMate Schools website homepage', url: 'studymateschools.com' },
        heroChecks: ['No setup fee', 'Free for 20 students', 'Works on any phone', 'We migrate your data'],
        cta: {
            primary: { label: 'Register your school — free', href: 'https://www.studymateschools.com/school/register' },
            secondary: { label: 'Request a walkthrough', href: '#enquire' },
            pricing: 'https://www.studymateschools.com/school-pricing',
        },
        audiences: [
            { title: 'Proprietors', text: 'See fees collected, attendance and results across every class — and every branch — from one dashboard.' },
            { title: 'Teachers', text: 'Take attendance, share lesson notes, set auto-graded assignments and publish report cards in minutes.' },
            { title: 'Parents', text: 'Check results, pay fees online and get absence alerts for all their children in one portal.' },
            { title: 'Students', text: 'Sit CBT exams, view assignments and get AI homework help in English, Igbo, Yoruba and Hausa.' },
        ],
        modules: [
            { title: 'Academics', icon: 'book', items: ['Classes, subjects, timetables and attendance', 'Lesson notes and auto-graded assignments', 'Continuous assessment and report cards (PDF)', 'Promotion, curriculum planning and transcripts'] },
            { title: 'Exams & results', icon: 'check', items: ['CBT exams with timer, shuffling and anti-cheat', 'Question bank and post-exam analytics', 'Online result checking by PIN or scratch card', 'WAEC, JAMB and NECO past questions'] },
            { title: 'Fees & finance', icon: 'ledger', items: ['Fee structures, receipts and online payment', 'Automatic fee reminders', 'School wallet and canteen till', 'Payroll with pension, tax and payslips'] },
            { title: 'Admissions & staff', icon: 'people', items: ['Online admission forms with document upload', 'Staff records, attendance and leave', 'Sub-admins and multi-branch schools', 'Student ID cards with QR codes'] },
            { title: 'Operations', icon: 'building', items: ['Transport routes and bus tracker', 'Hostels, inventory and requisitions', 'Alumni, events and bookings', 'School website builder and branded portal'] },
            { title: 'Communication', icon: 'chat', items: ['Bulk SMS and WhatsApp messaging', 'Announcements and direct messages', 'Parent absence alerts', 'Custom reports with Excel export'] },
        ],
        highlights: [
            { title: 'Built for how African schools work', text: 'Report cards in the familiar format, termly fees, scratch-card result checking and exam-body past questions.' },
            { title: 'AI learning included', text: 'Socratic homework helper, quizzes, flashcards and skills practice inside the student portal.' },
            { title: 'Your own branded portal', text: 'Every school gets its own subdomain, website and admissions page.' },
            { title: 'Secure by default', text: 'Two-factor authentication, audit log, encrypted fields and data-retention controls.' },
        ],
        faq: [
            { q: 'How long does setup take?', a: 'Most schools are set up in under ten minutes. Your first 20 students are always free, and we will move your existing records across for you.' },
            { q: 'Does it work on phones?', a: 'Yes. Every portal works in a mobile browser and can be installed like an app, so parents and teachers do not need a laptop.' },
            { q: 'Is there a student version?', a: 'Yes — StudyMate Naija (studymatenaija.com) is the same AI study buddy available directly to students and parents.' },
        ],
    },
    {
        slug: 'studymate-ums',
        name: 'Studymate UMS',
        mark: 'U',
        color: '#1f4d3a',
        category: 'education',
        status: 'live',
        kicker: 'University management',
        tagline: 'Students check their results. Lecturers run their courses. You run the institution.',
        summary: 'A complete university management platform built for African institutions — deployable per faculty, not just per university.',
        points: ['Registry, results, fees and LMS in one', 'Start with one faculty, scale campus-wide', 'Licensed by the institution — free for students'],
        site: 'https://studymateums.com',
        image: { src: '/img/studymate-ums.webp', alt: 'Studymate UMS website showing a student results dashboard', url: 'studymateums.com' },
        heroChecks: ['Deploy per faculty', 'Students pay nothing', 'Currently in pilot'],
        cta: {
            primary: { label: 'Request a demo', href: '#enquire' },
            secondary: { label: 'Visit studymateums.com', href: 'https://studymateums.com' },
        },
        audiences: [
            { title: 'Registrars & ICT directors', text: 'Structure from campus to course, admissions, registration and transcripts — with accreditation-ready exports.' },
            { title: 'Deans & HODs', text: 'Course offerings, lecturer workloads, result approval and academic standing at a glance.' },
            { title: 'Lecturers', text: 'Lesson notes, video lectures, live classes, CBT tests and bulk result upload.' },
            { title: 'Bursars', text: 'Fee structures, invoices, instalments, scholarships and Paystack collection.' },
        ],
        modules: [
            { title: 'Registry', icon: 'building', items: ['Campuses, colleges, departments and programmes', 'Admissions with admission letters', 'Course registration and approvals', 'Resits, deferrals and exam eligibility'] },
            { title: 'Results & records', icon: 'check', items: ['Continuous assessment and exam scores', 'GPA/CGPA on a 5-point scale with locked publishing', 'Transcripts, certificates and convocation', 'Public certificate and transcript verification'] },
            { title: 'Teaching & learning', icon: 'book', items: ['Lesson notes and video lectures', 'Live classes with recording', 'CBT engine with question banks and lockdown browser', 'Open & distance learning course materials workflow'] },
            { title: 'Finance', icon: 'ledger', items: ['Fee structures, invoices and credit notes', 'Instalment plans and scholarships', 'Hostel payments', 'Online collection via Paystack'] },
            { title: 'HR & campus services', icon: 'people', items: ['Staff, payroll, pension and leave', 'Recruitment and performance', 'Library, hostels, health records and ID cards', 'Disciplinary records'] },
            { title: 'Governance', icon: 'shield', items: ['Meetings, memos and actions', 'Research grants and asset register', 'Accreditation exports', 'Role-based dashboards and audit log'] },
        ],
        highlights: [
            { title: 'Start with one faculty', text: 'A single faculty or distance-learning centre can adopt it first. The rest of the university joins when ready.' },
            { title: 'Every score, not just a letter', text: 'Students see each test and exam component the moment results are published.' },
            { title: 'One place for course material', text: 'No more hunting through WhatsApp groups for last week\'s notes or a missing class link.' },
            { title: 'Isolated and secure', text: 'Row-level tenant isolation, two-factor sign-in, role-based access and a full audit trail.' },
        ],
        faq: [
            { q: 'How is it licensed?', a: 'The institution pays for a licence based on student numbers and chosen tier. Students are enrolled by administrators and pay nothing to use the platform.' },
            { q: 'Can we pilot it first?', a: 'Yes. Studymate UMS is designed to be deployed per faculty, and is currently in pilot with a faculty in Nigeria.' },
            { q: 'Do we get our own address?', a: 'Each university runs on its own subdomain with its own public website, news, events and admissions pages.' },
        ],
    },
    {
        slug: 'learnbee',
        name: 'LearnBee',
        mark: 'L',
        color: '#d97706',
        category: 'education',
        status: 'live',
        kicker: 'AI tutor · UK',
        tagline: 'Your child\'s AI study buddy.',
        summary: '24/7 homework help, smart quizzes and exam prep — aligned to the UK National Curriculum, from KS1 to A-Level.',
        points: ['Guides with questions, not answers', 'Quizzes, flashcards & skills practice', '14-day free trial, no card needed'],
        site: 'https://learnbee.co.uk',
        image: { src: '/img/learnbee.webp', alt: 'LearnBee website homepage with its bee mascot', url: 'learnbee.co.uk' },
        heroChecks: ['KS1 to A-Level', '14-day free trial', 'No credit card required'],
        cta: {
            primary: { label: 'Start free trial', href: 'https://learnbee.co.uk/register' },
            secondary: { label: 'Visit learnbee.co.uk', href: 'https://learnbee.co.uk' },
        },
        audiences: [
            { title: 'Students', text: 'Get unstuck on homework any time, then lock it in with quizzes, flashcards and exam practice.' },
            { title: 'Parents', text: 'A parent dashboard with per-child reports and weekly progress emails.' },
        ],
        modules: [
            { title: 'AI learning tools', icon: 'spark', items: ['Homework helper that teaches through questions', 'AI-generated quizzes with review', 'Flashcards with spaced repetition and read-aloud', 'Exam prep and revision timetables'] },
            { title: 'Skills practice', icon: 'check', items: ['Skill practice with mastery levels', 'Diagnostic reports', 'Personalised recommendations', 'Progress by skill'] },
            { title: 'Motivation', icon: 'people', items: ['Points, levels and streaks', 'Achievements and leaderboards', 'Challenges and study groups', 'Friends and group chat'] },
            { title: 'For parents', icon: 'shield', items: ['Parent dashboard', 'Link multiple children', 'Per-child progress reports', 'Weekly progress emails'] },
        ],
        highlights: [
            { title: 'Every subject they study', text: 'From primary maths to A-Level chemistry, plus English, science, economics and more.' },
            { title: 'Socratic by design', text: 'LearnBee helps children reason their way to the answer instead of handing it over.' },
            { title: 'Works everywhere', text: 'Installable on phones, tablets and laptops, with Google sign-in.' },
        ],
        faq: [
            { q: 'How much does it cost?', a: 'There is a free tier with daily limits. Premium is £9.99/month or £99.99/year for unlimited use on up to three devices, with a 14-day free trial.' },
            { q: 'Which curriculum does it follow?', a: 'LearnBee is aligned to the UK National Curriculum from Key Stage 1 through A-Level.' },
        ],
    },
    {
        slug: 'naijaxch',
        name: 'NaijaXch',
        mark: 'N',
        color: '#15803d',
        category: 'finance',
        status: 'soon',
        kicker: 'Stock research',
        tagline: 'Make NGX trend analysis fluid.',
        summary: 'Interactive charts, screeners and plain-English report cards for stocks listed on the Nigerian Exchange — research tools, not a broker.',
        points: ['Interactive charts with corporate-action adjustment', 'Screener, heatmap and report cards', 'Watchlists and portfolio tracking'],
        site: null,
        image: null,
        heroChecks: ['Research, not a broker', 'Free tier planned', 'Web-first'],
        cta: {
            primary: { label: 'Join early access', href: '#enquire' },
        },
        enquiry: { title: 'Get early access', text: 'NaijaXch is in final preparation ahead of launch. Leave your email and we\'ll let you know the moment it opens.', button: 'Join the list', kind: 'waitlist' },
        audiences: [
            { title: 'Retail investors', text: 'Understand how a Nigerian stock has really performed, adjusted for bonuses and splits.' },
            { title: 'Research-minded savers', text: 'Compare companies against their sector and their own history before you invest.' },
        ],
        modules: [
            { title: 'Trend charts', icon: 'chart', items: ['Timeframes up to 5 years and full history', 'Drag to read any point', 'Candlesticks and volume', 'Moving averages, Bollinger Bands, RSI and MACD'] },
            { title: 'Research', icon: 'check', items: ['Screener with one-click presets', 'Report cards with sector comparison', 'Plain-English AI summaries of computed figures', 'Official filings and corporate actions'] },
            { title: 'Your portfolio', icon: 'ledger', items: ['Watchlists', 'Manual portfolio tracker', 'Portfolio-level trend', 'Market heatmap and compare view'] },
        ],
        highlights: [
            { title: 'Numbers you can trust', text: 'Every figure is calculated from a clean, adjusted end-of-day price series — the AI only explains, it never invents numbers.' },
            { title: 'Clear about what it is', text: 'General information for research. No trading, no custody of funds, no personalised advice.' },
        ],
        faq: [
            { q: 'When does it launch?', a: 'We are completing data licensing ahead of launch. Join the early-access list and you will hear first.' },
            { q: 'Is this investment advice?', a: 'No. NaijaXch provides automated, general information to help you research — not personalised advice.' },
        ],
    },
    {
        slug: 'rosca',
        name: 'Rosca',
        mark: 'R',
        color: '#4f46e5',
        category: 'finance',
        status: 'soon',
        kicker: 'Group savings app',
        tagline: 'Save together, grow together.',
        summary: 'A mobile app that runs rotating savings groups — ajo, esusu, susu — with contribution tracking, automatic rotations and payouts.',
        points: ['Random, fixed-order or bidding rotations', 'Contribution tracking & reminders', 'Support collections for life events'],
        site: null,
        image: { src: '/img/rosca.webp', alt: 'Rosca mobile app screen', phone: true },
        heroChecks: ['iOS & Android', 'Invite-code groups', 'Built-in reminders'],
        cta: {
            primary: { label: 'Join the waitlist', href: '#enquire' },
        },
        enquiry: { title: 'Be first to try Rosca', text: 'Rosca is preparing for release on iOS and Android. Join the waitlist and we\'ll send you a download link at launch.', button: 'Join the waitlist', kind: 'waitlist' },
        audiences: [
            { title: 'Savings groups', text: 'Friends, families, colleagues and associations that already save together — without the notebook.' },
            { title: 'Group organisers', text: 'Stop chasing contributions over chat. Everyone can see who has paid and whose turn is next.' },
        ],
        modules: [
            { title: 'Groups', icon: 'people', items: ['Create a group and invite by code', 'Random draw, fixed order or bidding rotations', 'Clear schedule of whose turn is next'] },
            { title: 'Money', icon: 'ledger', items: ['Contribution tracking', 'Payout records and transaction history', 'Linked bank accounts'] },
            { title: 'Community', icon: 'chat', items: ['Support collections for weddings, bereavement, births and more', 'Notifications and payment reminders', 'Secure sign-in with Apple or Google'] },
        ],
        highlights: [
            { title: 'Fair rotations', text: 'Choose a random draw, a fixed order, or let members bid for an earlier payout.' },
            { title: 'Transparent for everyone', text: 'Every member sees the same record of contributions and payouts.' },
        ],
        faq: [
            { q: 'When will Rosca be available?', a: 'Rosca is preparing for release on the App Store and Google Play. Join the waitlist to get the download link at launch.' },
        ],
    },
];

export const bySlug = Object.fromEntries(solutions.map(s => [s.slug, s]));
